# -*- coding: utf-8 -*-
"""ml lab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Iy_a19wny455OKdg0oL6_vkpvsFYuNa-
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from google.colab import files
uploaded = files.upload()

df=pd.read_csv("car.csv")
print(df)
df.max()

buying= df.iloc[:,[0,3]]
persons= df.iloc[:,3]

print(buying)

print(persons)

from sklearn.model_selection import train_test_split

buying_train, buying_test, persons_train, persons_test = train_test_split(buying, persons, test_size=0.25, random_state=0)

print(buying_train, buying_test)

from sklearn.preprocessing import StandardScaler

st_buying= StandardScaler()
buying_train= st_buying.fit_transform(buying_train)
buying_test= st_buying.transform(buying_test)

print(buying_test)

from sklearn.tree import DecisionTreeClassifier
clf= DecisionTreeClassifier(criterion='entropy',random_state=0)
clf.fit(buying_train,persons_train)

persons_pred= clf.predict(buying_test)
print(persons_pred)

from sklearn.metrics import confusion_matrix
cm= confusion_matrix(persons_test,persons_pred)
print(cm)

import matplotlib as mpl
import matplotlib.pyplot as plt

plt.style.use('classic')

import matplotlib.pyplot as plt
import numpy as np
persons_pred= np.linspace(0, 10, 100)
plt.plot(persons_pred, np.sin(persons_pred))
plt.show()

persons_pred= clf.predict(buying_test)
plt.plot(persons_pred)
plt.show()

cm= confusion_matrix(persons_test,persons_pred)
plt.plot(cm)
plt.show()

from sklearn.tree import export_graphviz
import graphviz
graphviz.Source(export_graphviz(clf,feature_names=buying.columns,filled=True))



from sklearn import tree
buying,persons=buying.data,persons.data
clf=tree.DecisionTreeClassifier()
clf=clf.fit(buying,persons)
tree.plot_tree(clf)